name: supplies
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  easy_localization: ^3.0.7+1
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  google_maps_flutter: ^2.12.1
  dio: ^5.8.0+1
  mobile_scanner: ^6.0.10
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  fluttertoast: ^8.2.12
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.0
  infinite_scroll_pagination: ^5.0.0
  pinput: ^5.0.1

  dropdown_button2: ^2.3.9
  flutter_launcher_icons: ^0.14.3
  geolocator: ^10.1.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  # Add your image assets here
  assets:
    - assets/images/
    - assets/images/delete/
    - assets/translations/


  # Example font section if you want to add custom fonts in the future
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
